inherit_from:
  - '.thoughtbot.rubocop.yml'

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'

Style/BracesAroundHashParameters:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories.rb'

Style/SymbolArray:
  Enabled: false

Layout/IndentHash:
  Enabled: true
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories.rb'
